apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: eric-k8s-3
  name: eric-k8s-3
spec:
  imagePullSecrets:
  - name: regcred
  containers:
  - image: nginx
    name: eric-k8s-3
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
